const GET_USERS_SAGA = 'GET_USERS_SAGA';
const SET_USERS = 'SET_USERS';

const GET_TIME = 'GET_TIME';
const SET_GALLERY_INDEX = 'SET_GALLERY_INDEX';
const ADD_GALLERY_INDEX = 'ADD_GALLERY_INDEX';
const SUB_GALLERY_INDEX = 'SUB_GALLERY_INDEX';

export {  //eslint-disable-line
  GET_USERS_SAGA,
  SET_USERS,

  GET_TIME,

  SET_GALLERY_INDEX,
  ADD_GALLERY_INDEX,
  SUB_GALLERY_INDEX,
};
